### ISSUE TITLE
Atlas Kubernetes Operator, getting error when migration has "CREATE INDEX CONCURRENTLY"

### ISSUE THREAD

**Issue by vmrm** [ariga/atlas#1870]
Atlas Kubernetes Operator with 0.2.0 in k8s v1.25.11
When applying migrations containing:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrationdir-psql
data:
  20230712165510_create_tables.sql: |
    -- Add new schema named "cd"
    CREATE SCHEMA "cd";
    -- Create "facilities" table
    CREATE TABLE "cd"."facilities" ("facid" integer NOT NULL, "name" character varying(100) NOT NULL, "membercost" numeric NOT NULL, "guestcost" numeric NOT NULL, "initialoutlay" numeric NOT NULL, "monthlymaintenance" numeric NOT NULL, PRIMARY KEY ("facid"));
    -- Create "members" table
    CREATE TABLE "cd"."members" ("memid" integer NOT NULL, "surname" character varying(200) NOT NULL, "firstname" character varying(200) NOT NULL, "address" character varying(300) NOT NULL, "zipcode" integer NOT NULL, "telephone" character varying(20) NOT NULL, "recommendedby" integer NULL, "joindate" timestamp NOT NULL, PRIMARY KEY ("memid"), CONSTRAINT "members_recommendedby_fkey" FOREIGN KEY ("recommendedby") REFERENCES "cd"."members" ("memid") ON UPDATE NO ACTION ON DELETE SET NULL);
    -- Create "bookings" table
    CREATE TABLE "cd"."bookings" ("bookid" integer NOT NULL, "facid" integer NOT NULL, "memid" integer NOT NULL, "starttime" timestamp NOT NULL, "slots" integer NOT NULL, PRIMARY KEY ("bookid"), CONSTRAINT "bookings_facid_fkey" FOREIGN KEY ("facid") REFERENCES "cd"."facilities" ("facid") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "bookings_memid_fkey" FOREIGN KEY ("memid") REFERENCES "cd"."members" ("memid") ON UPDATE NO ACTION ON DELETE NO ACTION);
  20230712165923_create_indexes.sql: |
    -- Create index "bookings.facid_memid" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.facid_memid" ON "cd"."bookings" ("facid", "memid");
    -- Create index "bookings.facid_starttime" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.facid_starttime" ON "cd"."bookings" ("facid", "starttime");
    -- Create index "bookings.memid_facid" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.memid_facid" ON "cd"."bookings" ("memid", "facid");
    -- Create index "bookings.memid_starttime" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.memid_starttime" ON "cd"."bookings" ("memid", "starttime");
    -- Create index "bookings.starttime" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.starttime" ON "cd"."bookings" ("starttime");
    -- Create index "members.joindate" to table: "members"
    CREATE INDEX CONCURRENTLY "members.joindate" ON "cd"."members" ("joindate");
    -- Create index "members.recommendedby" to table: "members"
    CREATE INDEX CONCURRENTLY "members.recommendedby" ON "cd"."members" ("recommendedby");
  atlas.sum: |
    h1:xTbw3AxHRH3YSW7dOGteMxvcigM3f/Y7pdkwwScmbGM=
    20230712165510_create_tables.sql h1:BWXssdgcYxJcYSNOaK7bYlhgB5LsumtrNXiBfkC3HiU=
    20230712165923_create_indexes.sql h1:WQxGEQSGBr+QCZQB+/cRZ84Ei8Br2iJ9nbwC9/k2oW8=
```

We get:
```
Name:         atlasmigration-psql1
Namespace:    databases
Labels:       <none>
Annotations:  <none>
API Version:  db.atlasgo.io/v1alpha1
Kind:         AtlasMigration
Metadata:
  Creation Timestamp:  2023-07-17T17:18:37Z
  Generation:          1
  Managed Fields:
    API Version:  db.atlasgo.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:dir:
          .:
          f:configMapRef:
        f:urlFrom:
          .:
          f:secretKeyRef:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-07-17T17:18:37Z
    API Version:  db.atlasgo.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:lastApplied:
        f:observed_hash:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2023-07-17T17:22:23Z
  Resource Version:  53914104
  UID:               6c0ed890-5cbe-4383-85c3-ae9ff072b43a
Spec:
  Dir:
    Config Map Ref:
      Name:  migrationdir-psql
  URL From:
    Secret Key Ref:
      Key:   url
      Name:  psql1-creds
Status:
  Conditions:
    Last Transition Time:  2023-07-17T17:18:37Z
    Message:               sql/migrate: sql/migrate: execute: executing statement "CREATE INDEX CONCURRENTLY \"bookings.facid_memid\" ON \"cd\".\"bookings\" (\"facid\", \"memid\");" from version "20230712165923": pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block: sql/migrate: execute: write revision: pq: current transaction is aborted, commands ignored until end of transaction block
    Reason:                Reconciling
    Status:                False
    Type:                  Ready
  Last Applied:            0
  observed_hash:
Events:                    <none>
```

Same result for 11, 13, 15 PostgreSQLs spinning with CNPG Operator.

**Comment by a8m** [comment]
I think setting `txmode` to `none` in this current file should solve the issue, because the default behavior is running each file within a transaction. See: https://atlasgo.io/versioned/apply#file-level-transaction-mode

Can you try this and report if that solves the issue?

**Comment by vmrm** [comment]
I've tried using https://atlasgo.io/versioned/apply#file-level-transaction-mode
```
  20230712165923_create_indexes.sql: |
    -- atlas:txmode none
    -- Create index "bookings.facid_memid" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.facid_memid" ON "cd"."bookings" ("facid", "memid");
    -- Create index "bookings.facid_starttime" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.facid_starttime" ON "cd"."bookings" ("facid", "starttime");
    -- Create index "bookings.memid_facid" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.memid_facid" ON "cd"."bookings" ("memid", "facid");
    -- Create index "bookings.memid_starttime" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.memid_starttime" ON "cd"."bookings" ("memid", "starttime");
    -- Create index "bookings.starttime" to table: "bookings"
    CREATE INDEX CONCURRENTLY "bookings.starttime" ON "cd"."bookings" ("starttime");
    -- Create index "members.joindate" to table: "members"
    CREATE INDEX CONCURRENTLY "members.joindate" ON "cd"."members" ("joindate");
    -- Create index "members.recommendedby" to table: "members"
    CREATE INDEX CONCURRENTLY "members.recommendedby" ON "cd"."members" ("recommendedby");
```
but still getting the:
```
Status:
  Conditions:
    Last Transition Time:  2023-07-17T18:15:58Z
    Message:               sql/migrate: sql/migrate: execute: executing statement "CREATE INDEX CONCURRENTLY \"bookings.facid_memid\" ON \"cd\".\"bookings\" (\"facid\", \"memid\");" from version "20230712165923": pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block: sql/migrate: execute: write revision: pq: current transaction is aborted, commands ignored until end of transaction block
    Reason:                Reconciling
    Status:                False
    Type:                  Ready
```
After changing file to:
```
  20230712165923_create_indexes.sql: |
    -- atlas:txmode none

    CREATE INDEX CONCURRENTLY "bookings.facid_memid" ON "cd"."bookings" ("facid", "memid");
    CREATE INDEX CONCURRENTLY "bookings.facid_starttime" ON "cd"."bookings" ("facid", "starttime");
    CREATE INDEX CONCURRENTLY "bookings.memid_facid" ON "cd"."bookings" ("memid", "facid");
    CREATE INDEX CONCURRENTLY "bookings.memid_starttime" ON "cd"."bookings" ("memid", "starttime");
    CREATE INDEX CONCURRENTLY "bookings.starttime" ON "cd"."bookings" ("starttime");
    CREATE INDEX CONCURRENTLY "members.joindate" ON "cd"."members" ("joindate");
    CREATE INDEX CONCURRENTLY "members.recommendedby" ON "cd"."members" ("recommendedby");
```
```
Status:
  Conditions:
    Last Transition Time:  2023-07-17T18:20:20Z
    Message:
    Reason:                Applied
    Status:                True
    Type:                  Ready
  Last Applied:            1689618018
  Last Applied Version:    20230712165923
  observed_hash:           d721437cb2fc4821a74764784a86d7feb6e4da758b40df28a7bac07151edf7ec
```
everything worked as expected. Thanks! Not sure if comments are breaking some parsing.

**Comment by a8m** [comment]
A file directive should be separated by two newlines from the first statement's comment.

Closing as the issue was resolved. You're more than welcome to join our [Discord server](https://discord.gg/zZ6sWVg6NT) in case you need more help with it.

**Comment by vmrm** [comment]
Thanks a lot for your help!

**Comment by hosseindehghanpoor** [comment]
@vmrm 
how did you calculate atlas.sum ?
can you explain it to me

  atlas.sum: |
    h1:xTbw3AxHRH3YSW7dOGteMxvcigM3f/Y7pdkwwScmbGM=
    20230712165510_create_tables.sql h1:BWXssdgcYxJcYSNOaK7bYlhgB5LsumtrNXiBfkC3HiU=
    20230712165923_create_indexes.sql h1:WQxGEQSGBr+QCZQB+/cRZ84Ei8Br2iJ9nbwC9/k2oW8=

**Comment by rotemtam** [comment]
Use `atlas migrate hash`

**Comment by hosseindehghanpoor** [comment]
@rotemtam 
can you give me more details please. im not sure how to use it.
i have a couple of XXX.sql files and i am going to use atlas kubernetes operator to migrate my test database. 
 
 i am not sure how to calcute the atlas.sum content in atlas-migrate-configmap.yaml
