### ISSUE TITLE
Unexpected view definition on v0.13.0

### ISSUE THREAD

**Issue by RD211** [ariga/atlas#1960]
I managed my migrations for a Supabase instance using Atlas, and after the new version dropped, migrations stopped working.

I get this error while running supabase locally.
```
Error: unexpected empty view definition was returned for "extensions"."pg_stat_statements"
```

**Comment by a8m** [comment]
Hey @RD211, just to help me reproducing it, do you use [this](https://hub.docker.com/r/supabase/postgres) docker image? Also, can you please paste here an example URL you use for connecting your database (mask the password, ofc)?

**Comment by RD211** [comment]
I ran it with Supabase installed with npm but I suppose the docker image would also work.

I use this database connection.
```
postgresql://postgres:postgres@localhost:54322/postgres?sslmode=disable
```

And run this exact command:
```
atlas migrate apply --dir file://migrations/ -u ${DATABASE_URL} --allow-dirty
```

Setting the version to the previous one works:
```
export ATLAS_VERSION="v0.12.2-d9829c8-canary"
```

The migrations are nothing complex but I suppose this fails before running them anyway.

I have not tested this on Supabase hosted on their servers but just locally. In any case I suppose testing with their instance would be easier if still present.

**Comment by a8m** [comment]
Thanks for the detailed report, David. I think I found the issue (and it has been fixed now) - I'll appreciate it if you can pull a new binary and confirm this.

The problem was that, similar to the way we handle table inspection, we need to ignore views that are created by installed/loaded extensions. Filtering them now on inspection solved the issue for me.

**Comment by RD211** [comment]
On this version: 
```
atlas version v0.13.1-39aa6b1-canary
```

It says this now: 
```
Error: unexpected empty view definition was returned for "vault"."decrypted_secrets"
```
The error did change but I suppose this table is not created by an extension and that's why this still persists.

**Comment by a8m** [comment]
Thanks, I'll try to reproduce this on Supabase's PostgreSQL image.

Do you work on multiple PostgreSQL schemas, or just `public`? Because setting the URL without `search_path=<schema>` tells Atlas to scan the entire `postgres` database. See: https://atlasgo.io/concepts/url

**Comment by a8m** [comment]
Hey @RD211 👋 

I want to update you that I was able to reproduce the issue, and I found that the error is returned due to a lack of permissions for the connected user to query information_schema.views. Here are a few simple steps to reproduce this:

PostgreSQL:
```sql
CREATE USER a8m PASSWORD 'pass';
REVOKE SELECT ON TABLE information_schema.views FROM a8m;
CREATE VIEW v AS SELECT 1;
GRANT SELECT ON v TO a8m;
```

Atlas:
```bash
$ atlas schema inspect -u "postgres://a8m:pass@:5432/postgres?sslmode=disable"
Error: unexpected empty view definition was returned for "public"."v"
```

Following my question above:
- Is there any reason you query the entire database?
- Changing the user permissions should solve the issue, but I don't think the intention was to manage these internal views/tables, right? Would you expect Atlas to just ignore them in this case?

**Comment by RD211** [comment]
Hi! Thanks for the help with this!

- Do you mean that a fix would be to only look at some of the schemas instead? If so, yeah, that should work for me. I am not interacting with any other schemas besides public and storage.

- Yes, I did not want to manage those at all, so I guess either ignoring them or not looking at all at those schemas could also work.

I found something in the docs to only look at some schemas, so I think I will try that as that would be the easiest option.

**Comment by a8m** [comment]
> Do you mean that a fix would be to only look at some of the schemas instead? If so, yeah, that should work for me. I am interacting with public but also with storage directly so that's why I did not put a search_path but I suppose there is a way to select more than one schema.

Yes. There are options to specify schemas in flags or config file.

> I found something in the docs to only look at some schemas, so I think I will try that, as that would be the easiest option.

OK, please give it a try and let me know if we can close this issue, or there's a fix needed for it. Thanks 🙏

**Comment by RD211** [comment]
Yup seemed to work for me!
Thanks for the help!

**Comment by mcaxtrzen** [comment]
Hi! I got a similar problem with Atlas v0.13.1 but it's related to Materialized Views instead. It says:

Error: view "my_materialized_view" was not found in schema "my_schema"

**Comment by mcaxtrzen** [comment]
Hello @a8m have you had a chance to take a look on this?

**Comment by a8m** [comment]
Hey, @mcaxtrzen! I missed your previous comment. 

Altas currently does not support materialized views (this should be added soon), and the inspection fails as Atlas can't find the `my_materialized_view` (materialized) view as a dependency. I'll send a patch to fix this and will let you know when it's ready.

**Comment by mcaxtrzen** [comment]
Awesome @a8m thank you!

**Comment by mcaxtrzen** [comment]
Great, it works fine now! Thanks a lot!
