### ISSUE TITLE
Exclude views?

### ISSUE THREAD

**Issue by mcaxtrzen** [ariga/atlas#2017]
Hi,

I'm trying to exclude views when inspecting an schema, but it doesn't seem to work. It works fine for tables though.

Is the `--exclude` flag implemented for views yet?

Congrats for the awesome tool.

**Comment by a8m** [comment]
Thanks for reporting this, @mcaxtrzen.

The issue was resolved with #2018. New binaries should be released in 20 minutes. Please, re-install Atlas and let me know if you encounter any other issues with it. Thanks

**Comment by mcaxtrzen** [comment]
Hello @a8m. Thanks for the reply.

I'm not sure if I'm doing something wrong, but unfortunately I still get the same result. When I run

`atlas schema inspect -u "postgres://${USER}:${PASSWORD}@0.0.0.0:5432/${DATABASE}?sslmode=disable" --exclude "*.table*"`

it doesn't return any table as expected, but when I run

`atlas schema inspect -u "postgres://${USER}:${PASSWORD}@0.0.0.0:5432/${DATABASE}?sslmode=disable" --exclude "*.view*"`

it returns everything, including the views. 

Another thing I noticed is that now the inspect returns the table resources in a different format when I inspect multiple schemas. It used to be

```
table "table_name" {
    schema = schema.schema_name    
    ...
}
```

And now it returns 

```
table "schema_name" "table_name" {
    schema = schema.schema_name    
    ...
}
```

It doesn't happen when I inspect only one schema, in this case it returns as expected

```
table "table_name" {
    schema = schema.schema_name    
    ...
}
```


I'm using latest version (v0.13.3-32b4f04-canary).

**Comment by a8m** [comment]
Hey @mcaxtrzen, use the following pattern to exclude views:

```
*.*[type=view]
*.prefix*[type=view]
```
For more examples, see: https://atlasgo.io/declarative/inspect#exclude-tables

> Another thing I noticed is that now the inspect returns the table resources in a different format when I inspect multiple schemas. It used to be

When inspecting multiple schemas, if there are two tables with the same name (residing in two different schemas), they get qualified, the same as in SQL. If we don't qualify them, you can't reference them (in HCL) as there's ambiguity in the schema.

**Comment by mcaxtrzen** [comment]
Hi @a8m,

I got the same result with both `*.*[type=view]` and `*.prefix*[type=view]`

```
atlas schema inspect -u "postgres://${USER}:${PASSWORD}@0.0.0.0:5432/${DATABASE}?sslmode=disable" --exclude "*.*[type=view]"
table "table1" {
  schema = schema.schema1
  column "name" {
    null = false
    type = text
  }
  column "id" {
    null = false
    type = text
  }
}
view "view1" {
  schema = schema.schema1
  column "test" {
    null = true
    type = bigint
  }
  as         = <<-SQL
   SELECT count(1) AS c
     FROM schema1.table1;
  SQL
  depends_on = [table.table1]
}
schema "schema1" {
}
```

```
atlas schema inspect -u "postgres://${USER}:${PASSWORD}@0.0.0.0:5432/${DATABASE}?sslmode=disable" --exclude "*.view*[type=view]"
table "table1" {
  schema = schema.schema1
  column "name" {
    null = false
    type = text
  }
  column "id" {
    null = false
    type = text
  }
}
view "view1" {
  schema = schema.schema1
  column "test" {
    null = true
    type = bigint
  }
  as         = <<-SQL
   SELECT count(1) AS c
     FROM schema1.table1;
  SQL
  depends_on = [table.table1]
}
schema "schema1" {
}
```

**Comment by a8m** [comment]
Marcus, if the scope of the connection is a schema (schema1 in this case), then the first part in the `exclude` is table/view and not a schema. Please run this with: `*[type=view]` and report if that solves the issue. Thanks

**Comment by mcaxtrzen** [comment]
Hey Ariel, I'm not sure if I understand your comment, the scope seems to be database, not schema (it's postgres). Am I missing something? In any case, I still got the same result 😞 

```
atlas schema inspect -u "postgres://${USER}:${PASSWORD}@0.0.0.0:5432/${DATABASE}?sslmode=disable" --exclude "*[type=view]"
table "table1" {
  schema = schema.schema1
  column "name" {
    null = false
    type = text
  }
  column "id" {
    null = false
    type = text
  }
}
view "view1" {
  schema = schema.schema1
  column "test" {
    null = true
    type = bigint
  }
  as         = <<-SQL
   SELECT count(1) AS c
     FROM schema1.table1;
  SQL
  depends_on = [table.table1]
}
schema "schema1" {
}
```

**Comment by a8m** [comment]
Oh! I see the problem now. Sorry, that's not the latest version - the binary was just built two hours ago (my mistake). Try to pull the new version and try again, please. The latest one includes my fix.

**Comment by mcaxtrzen** [comment]
Works like a charm! Thanks very much 😄
